# custom.py
# DO NOT EDIT THIS FILE
# command line: scons platform=web target=template_debug threads=no profile=custom.py build_profile=final_4.build
# command line: scons platform=web target=template_release threads=no

# run this every time after opening terminal
# cd Emscripten/emsdk
# emsdk_env.bat
# cd ../..

# # base
# debug_symbols="no"
# tools="no"

# # https://docs.godotengine.org/en/4.4/contributing/development/compiling/optimizing_for_size.html
# lto="full"
# optimize="size"
# module_text_server_adv_enabled="yes"
# module_text_server_fb_enabled="no"
# disable_3d="yes"
# disable_advanced_gui="no"

# options
deprecated="no"
minizip="no"
vulkan="no"
use_volk="no"

# Generated using https://godot-build-options-generator.github.io
module_basis_universal_enabled = "no"
module_bmp_enabled = "no"
module_camera_enabled = "no"
module_csg_enabled = "no"
module_dds_enabled = "no"
module_enet_enabled = "no"
module_gltf_enabled = "no"
module_gridmap_enabled = "no"
module_hdr_enabled = "no"
module_jsonrpc_enabled = "no"
module_ktx_enabled = "no"
module_meshoptimizer_enabled = "no"
module_minimp3_enabled = "no"
module_mobile_vr_enabled = "no"
module_multiplayer_enabled = "no"
module_navigation_enabled = "no"
module_noise_enabled = "no"
module_ogg_enabled = "no"
module_openxr_enabled = "no"
module_raycast_enabled = "no"
module_squish_enabled = "no"
module_tga_enabled = "no"
module_theora_enabled = "no"
module_upnp_enabled = "no"
module_vhacd_enabled = "no"
module_vorbis_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"
module_zip_enabled = "no"

"""
Tests

custom.py
base - works
base: debug_symbols="no" tools="no"
optimizing for size - works
optimizing for size: lto="full" optimize="size" module_text_server_adv_enabled="yes" module_text_server_fb_enabled="no" disable_3d="yes" disable_advanced_gui="no"
options - fails
minizip disabled & brotli disabled - works
minizip disabled & brotli enabled - works
minizip enabled & brotli disabled - fails
options: deprecated="no" minizip="no" vulkan="no" use_volk="no"

godot build options generator: 
module_basis_universal_enabled = "no"
module_bmp_enabled = "no"
module_camera_enabled = "no"
module_csg_enabled = "no"
module_dds_enabled = "no"
module_enet_enabled = "no"
module_gltf_enabled = "no"
module_gridmap_enabled = "no"
module_hdr_enabled = "no"
module_jsonrpc_enabled = "no"
module_ktx_enabled = "no"
module_meshoptimizer_enabled = "no"
module_minimp3_enabled = "no"
module_mobile_vr_enabled = "no"
module_multiplayer_enabled = "no"
module_navigation_enabled = "no"
module_noise_enabled = "no"
module_ogg_enabled = "no"
module_openxr_enabled = "no"
module_raycast_enabled = "no"
module_squish_enabled = "no"
module_tga_enabled = "no"
module_theora_enabled = "no"
module_upnp_enabled = "no"
module_vhacd_enabled = "no"
module_vorbis_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"
module_zip_enabled = "no"

this leaves the following enabled:
- OpenGL
- FreeType
- GDScript
- JPG
- mbedTLS
- MSDFGen
- RegEx
- SVG
- Text Server Advanced

custom_1.build - 29.5 MB
summary: in the general section keep only 2d physics and disable everything else
- 3d engine
- 3d physics
- navigation
- xr
- rendering device
- vulkan

custom_2.build - fails
summary: node stripping phase 1. disable animation, audio, all 3d resources, and unnecessary 2d resources
- sil graphite fonts
- animation mixer
- audio stream player
- flow container
- graph element
- scroll container
- split container
- sub viewport container
- tab container
- graph edit
- item list
- tree
- video stream player
- audio listener 2d - bone2d
- rigidbody2d
- staticbody2d
- collision polygon2d - raycast2d
- multiplayer spawner - node 3d

custom_2.build - 28.6 MB
summary: node stripping phase 1. disable animation, audio, all 3d resources, and unnecessary 2d resources
- sil graphite fonts
- animation mixer
- audio stream player
- audio listener 2d - bone2d
- rigidbody2d
- staticbody2d
- collision polygon2d - raycast2d
- multiplayer spawner - node 3d

custom_3.build - 27.6 MB
summary: resources stripping phase 1. disable animation, audio, curve, gltf etc
- animation - audio stream
- cryptokey - curve 3d
- gdextension - gltf texture sampler
- shape 3d
- texture 3d
- translation - video stream playback
- voxel gidata - world 3d

custom_4.build - 27.5 MB
summary: resources stripping phase 2. disable additional resources, all meshes
- importer mesh
- mesh
- mesh library
- missing resource
- multi mesh
- navigation mesh - openxrinteraction profile

custom_5.build - 27.3 MB
summary: node stripping phase 2. disable containers, scroll, and slider
- flow container
- graph element
- scroll container - tab container
- scroll bar
- slider
- remote transform 2d - skeleton 2d
- missing node

custom_6.build - 26.7 MB
summary: resources stripping phase 2. remove some compositor. remove rigging, editor resources, and tiles
- bonemap
- compositor
- compositor effect
- lightmap gi data
- skeleton modification 2d - skeleton profile
- sky
- syntax highlighter
- tilemap pattern - tile set source

custom_7.build - 25.8 MB not sure if it works or not, didn't test lol
summary: node stripping phase 2. unused nodes (hopefully) and expirimental nodes
- graph edit
- item list
- seperator
- tab bar
- text edit
- video stream player
- camera 2d
- tilemap
- tilemap layer
- status indicator
- timer

custom_8.build - 25.5 MB
summary: resources stripping phase 3. disable intense rendering resources
- camera attributes
- material
- scene replication config
- texture layered

final_1 - 25.4 MB

custom_9.build
summary: there is literally nothing left to strip wtf
- touch screen button
- visible on screen notifier 2d
- parallax background
custom_10.build
summary: idk what more to strip
- polygon path finder
- rd shader file
- rd shader spirv
- script extension
- visual shader node texture 3d parameter
- visual shader node sample 3d

final_2 - 24.4 MB
summary: if this doesn't do it, im fucking breaking the pencil in front of me
- checkbox
- color picker button
- visual shader node

final_3 - 24.7 MB
summary: adding some shit back
- remove global shader
- node elements
- bring back all buttons
- tab, seperator, split

final_4 - 24.8 MB
summary: moving more shit around
- remove input event joypad button + motion
- remove input event midi
- bring back the following: scroll container, split container, sub viewport container, tab container, scroll bar, slider

final_5 - 24.8 MB
summary: re-enable timer node
- bring back timer node

"""
